FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y file vim git gnupg2 wget python3 python3-pip tar zip unzip rsync zstd patchelf htop
RUN pip3 install meson

RUN bash -c 'echo "deb https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu focal main" > /etc/apt/sources.list.d/ubuntu-toolchain-r-test.list' && \
    bash -c 'echo "deb-src https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu focal main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r-test.list'
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C8EC952E2A0E1FBDC5090F6A2C277A0A352154E5
RUN apt update && apt install -y build-essential gcc-13 g++-13
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 130 --slave /usr/bin/g++ g++ /usr/bin/g++-13

RUN wget https://github.com/Kitware/CMake/releases/download/v3.31.9/cmake-3.31.9.tar.gz -O cmake.tar.gz
RUN mkdir cmake && tar -xzvf cmake.tar.gz --strip-components=1 -C cmake
RUN cd cmake && ./bootstrap --parallel=8 -- -DCMAKE_USE_OPENSSL=OFF -DBUILD_TESTING=OFF && \
    make -j8 && make install && \
    cd .. && rm -rf cmake cmake.tar.gz

RUN wget https://github.com/ccache/ccache/releases/download/v4.12.1/ccache-4.12.1-linux-x86_64.tar.xz -O ccache.tar.xz
RUN mkdir ccache && tar -xJf ccache.tar.xz --strip-components=1 -C ccache
RUN cd ccache && make install && \
    cd .. && rm -rf ccache ccache.tar.xz

RUN wget https://github.com/ninja-build/ninja/releases/download/v1.13.1/ninja-linux.zip -O ninja.zip
RUN mkdir ninja && unzip ninja.zip -d ninja
RUN cd ninja && mv ninja /usr/bin/ && \
    cd .. && rm -rf ninja ninja.zip

RUN apt update && apt install -y \
    autoconf xsltproc bison flex gperf python3 python3-dev \
    libcups2-dev libxml2-dev libnss3-dev libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

# without junit4, openjdk-17-jdk doxygen
RUN apt update && apt install -y \
    git zip libkrb5-dev nasm graphviz python3 python3-dev python3-setuptools \
    qtbase5-dev libkf5coreaddons-dev libkf5i18n-dev libkf5config-dev libkf5windowsystem-dev libkf5kio-dev libqt5x11extras5-dev \
    autoconf libcups2-dev libfontconfig1-dev gperf libxslt1-dev xsltproc libxml2-utils \
    libxrandr-dev libx11-dev bison flex libgtk-3-dev \
    libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev \
    ant ant-optional libnss3-dev libavahi-client-dev libxt-dev

RUN rm -rf /var/lib/apt/lists/*
